string id                             #robot id, format is "puppy-01", "puppy-02", ...
bool reset                            #reset flag
float32 pos_front_left_upper_des      #desired angular position for upper limb of front left leg 
float32 pos_front_left_lower_des      #desired angular position for lower limb of front left leg
float32 pos_rear_left_upper_des        #desired angular position for upper limb of rear left leg 
float32 pos_rear_left_lower_des       #desired angular position for lower limb of rear left leg
float32 pos_front_right_upper_des     #desired angular position for upper limb of front right leg 
float32 pos_front_right_lower_des     #desired angular position for lower limb of front right leg
float32 pos_rear_right_upper_des      #desired angular position for upper limb of rear right leg 
float32 pos_rear_right_lower_des      #desired angular position for lower limb of rear right leg
